# WARNING: Don’t use this unless for testing purposes. It’s gonna build shit.
name: hello
description: |
  A test package.

  It really doesn’t do anything more than printing (translated) hello worlds,
  so it’s a perfect test package.
version: 2.8
release: 1
source: http://ftp.gnu.org/gnu/hello/hello-2.8.tar.gz -> hello-2.8.tar.gz
license: GPL
depends:
  - blah >= 1.2
  - libfoo
url: http://hello.example
groups: [system, shell]

build-depends:

# Occasionally required features.
configure:
  cd src/hello-2.8;
  ./configure --prefix=/usr --mandir=/usr/man;
build:
  cd src/hello-2.8;
  make;
install:
  cd src/hello-2.8;
  make DESTDIR="$(pwd)/../../pkg" install;

splits:
  - name: libhello
    license: LGPL
    depends:
      - -blah
      - libfoo
    split:
      - $libdir

# Complex features. Never required.
use:
  -
    flag: nls
    depends:
      - +gettext
      - blah >= 1.4
      - -libfoo

